### PR TITLE
Stevenn pharma new

### PR DESCRIPTION
**Pull request by steve111MV**
hello @pierrepo  , i think this one is mergable. feedback expected in order to see how @ricken07  can rebase and continu.

### CODE REVIEW

**Comment by steve111MV** [comment]
@pierrepo the are conflicts,, i am on.

**Comment by pierrepo** [comment]
Sorry but lines starting by:
-  `+<<<<<<<`
-  `+=======`
- `+>>>>>>>`

must disapear !! These are signs of a previous merge conflict. They have been added by git.

**Comment by pierrepo** [comment]
There is still issue with pharmacie Galien and Teven that seem located as the same place!

Once everything will be OK. Please do not merge it yourself. I will perform a strong quality control myself.

**Comment by steve111MV** [comment]
ok

**Pull request closed without merging**
